# Generated by Django 6.1.1 on 2026-09-16 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="daily_fee",
            new_name="daily_free",
        ),
    ]
